alias dot='git --git-dir=/home/tor/.dotfiles/ --work-tree=/home/tor'
alias cp='cp -i'; alias mv='mv -i'; alias rm='rm -i'
alias ll='ls -alF'; alias la='ls -A'; alias ..='cd ..'; alias ...='cd ../..'; alias c='clear'
alias gs='git status'; alias ga='git add .'; alias gc='git commit -m'; alias gp='git push'; alias gco='git checkout'; alias gb='git branch'; alias gl='git log --oneline --graph --decorate'
alias venv='(command -v python3 >/dev/null && python3 -m venv venv || python -m venv venv) && . venv/bin/activate'
alias server-local='python3 -m http.server 9000 --bind 127.0.0.1'
alias server-lan='python3 -m http.server 9000'
alias snapcreate='sudo snapper -c root create --userdata "important=yes" --description'
alias codex-u='sudo npm install -g @openai/codex@latest'
alias safe-upgrade='sudo timeshift --create --comments "Before apt upgrade" && sudo apt update && sudo apt upgrade -y'
alias make_venv="~/.zsh/make_venv.sh"
alias gh-new='echo -n "Repository name: "; read repo; gh repo create "$repo" --private --source=. --remote=origin --push --confirm'
alias od='cd "/mnt/c/Users/TorHabberstad/OneDrive - Personalkollen Sverige AB"'
alias down='cd /mnt/c/Users/TorHabberstad/Downloads'
alias codex='command codex --dangerously-bypass-approvals-and-sandbox'
alias stdvenv='source ~/.stdvenv/bin/activate'
alias mountgdriveth='sudo mkdir -p /mnt/gdrive-th && sudo mount -t nfs nas:/volume1/gdrive-th /mnt/gdrive-th'
alias mountmedia='sudo mkdir -p /mnt/media && sudo mount -t nfs nas:/volume1/media /mnt/media'
